//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easylogsAPI.Application.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserService_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserService_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easylogsAPI.Application.Resources.Services.UserService.en-US", typeof(UserService_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot eliminate itself.
        /// </summary>
        internal static string CannotEliminateItself {
            get {
                return ResourceManager.GetString("CannotEliminateItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity validation failed.
        /// </summary>
        internal static string IdentityValidationFailed {
            get {
                return ResourceManager.GetString("IdentityValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect argument for &quot;Permissions&quot;.
        /// </summary>
        internal static string IncorrectArgumentPermission {
            get {
                return ResourceManager.GetString("IncorrectArgumentPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate has a incorrect format.
        /// </summary>
        internal static string IncorrectFormatEndDate {
            get {
                return ResourceManager.GetString("IncorrectFormatEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate has a incorrect format.
        /// </summary>
        internal static string IncorrectFormatStartDate {
            get {
                return ResourceManager.GetString("IncorrectFormatStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an administrator can grant administrator permissions.
        /// </summary>
        internal static string OnlyAnAdministratorCanGrantAdministratorPermissions {
            get {
                return ResourceManager.GetString("OnlyAnAdministratorCanGrantAdministratorPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;EndDate&quot; and &quot;StartDate&quot; are required.
        /// </summary>
        internal static string RequiredArgumentEndDateAndStartDate {
            get {
                return ResourceManager.GetString("RequiredArgumentEndDateAndStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Permissions&quot; is a required argument.
        /// </summary>
        internal static string RequiredArgumentPermissions {
            get {
                return ResourceManager.GetString("RequiredArgumentPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;StartDate&quot; and &quot;EndDate&quot; are required.
        /// </summary>
        internal static string RequiredArgumentStartDateAndEndDate {
            get {
                return ResourceManager.GetString("RequiredArgumentStartDateAndEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created correctly.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted correctly.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address registered.
        /// </summary>
        internal static string UserEmailRegistered {
            get {
                return ResourceManager.GetString("UserEmailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated correctly.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered user name.
        /// </summary>
        internal static string UserUsernameRegistered {
            get {
                return ResourceManager.GetString("UserUsernameRegistered", resourceCulture);
            }
        }
    }
}
