//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easylogsAPI.Application.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserService_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserService_es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easylogsAPI.Application.Resources.Services.UserService.es-ES", typeof(UserService_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminarse a si mismo.
        /// </summary>
        internal static string CannotEliminateItself {
            get {
                return ResourceManager.GetString("CannotEliminateItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validación de identidad fallida.
        /// </summary>
        internal static string IdentityValidationFailed {
            get {
                return ResourceManager.GetString("IdentityValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrecto argumento de &quot;Permissions.
        /// </summary>
        internal static string IncorrectArgumentPermission {
            get {
                return ResourceManager.GetString("IncorrectArgumentPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de fin tiene un formato incorrecto.
        /// </summary>
        internal static string IncorrectFormatEndDate {
            get {
                return ResourceManager.GetString("IncorrectFormatEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio tiene un formato incorrecto.
        /// </summary>
        internal static string IncorrectFormatStartDate {
            get {
                return ResourceManager.GetString("IncorrectFormatStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicamente un administrador, puede otorgar permisos de administrador.
        /// </summary>
        internal static string OnlyAnAdministratorCanGrantAdministratorPermissions {
            get {
                return ResourceManager.GetString("OnlyAnAdministratorCanGrantAdministratorPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de fin y de inicio son requeridas.
        /// </summary>
        internal static string RequiredArgumentEndDateAndStartDate {
            get {
                return ResourceManager.GetString("RequiredArgumentEndDateAndStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Permissions&quot; es un permiso requerido.
        /// </summary>
        internal static string RequiredArgumentPermissions {
            get {
                return ResourceManager.GetString("RequiredArgumentPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio y defin son requeridas.
        /// </summary>
        internal static string RequiredArgumentStartDateAndEndDate {
            get {
                return ResourceManager.GetString("RequiredArgumentStartDateAndEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado correctamente.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario eliminado correctamente.
        /// </summary>
        internal static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electronico registrado.
        /// </summary>
        internal static string UserEmailRegistered {
            get {
                return ResourceManager.GetString("UserEmailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizado correctamente.
        /// </summary>
        internal static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario registrado.
        /// </summary>
        internal static string UserUsernameRegistered {
            get {
                return ResourceManager.GetString("UserUsernameRegistered", resourceCulture);
            }
        }
    }
}
